struct GBOpcode
{
    const char* pMnemonic;
    uint8_t arguments;
};

static constexpr GBOpcode opcodeDisassembly[] = {
{ "NOP", 1 }, { "LD BC d16", 3 }, { "LD (BC) A", 1 }, { "INC BC", 1 }, { "INC B", 1 }, { "DEC B", 1 }, { "LD B d8", 2 }, { "RLCA", 1 }, { "LD (a16) SP", 3 }, { "ADD HL BC", 1 }, { "LD A (BC)", 1 }, { "DEC BC", 1 }, { "INC C", 1 }, { "DEC C", 1 }, { "LD C d8", 2 },
{ "RRCA", 1 }, { "STOP d8", 2 }, { "LD DE d16", 3 }, { "LD (DE) A", 1 }, { "INC DE", 1 }, { "INC D", 1 }, { "DEC D", 1 }, { "LD D d8", 2 }, { "RLA", 1 }, { "JR r8", 2 }, { "ADD HL DE", 1 }, { "LD A (DE)", 1 }, { "DEC DE", 1 }, { "INC E", 1 }, { "DEC E", 1 },
{ "LD E d8", 2 }, { "RRA", 1 }, { "JR NZ r8", 2 }, { "LD HL d16", 3 }, { "LD (HL) A", 1 }, { "INC HL", 1 }, { "INC H", 1 }, { "DEC H", 1 }, { "LD H d8", 2 }, { "DAA", 1 }, { "JR Z r8", 2 }, { "ADD HL HL", 1 }, { "LD A (HL)", 1 }, { "DEC HL", 1 }, { "INC L", 1 },
{ "DEC L", 1 }, { "LD L d8", 2 }, { "CPL", 1 }, { "JR NC r8", 2 }, { "LD SP d16", 3 }, { "LD (HL) A", 1 }, { "INC SP", 1 }, { "INC (HL)", 1 }, { "DEC (HL)", 1 }, { "LD (HL) d8", 2 }, { "SCF", 1 }, { "JR C r8", 2 }, { "ADD HL SP", 1 }, { "LD A (HL)", 1 }, { "DEC SP", 1 },
{ "INC A", 1 }, { "DEC A", 1 }, { "LD A d8", 2 }, { "CCF", 1 }, { "LD B B", 1 }, { "LD B C", 1 }, { "LD B D", 1 }, { "LD B E", 1 }, { "LD B H", 1 }, { "LD B L", 1 }, { "LD B (HL)", 1 }, { "LD B A", 1 }, { "LD C B", 1 }, { "LD C C", 1 }, { "LD C D", 1 },
{ "LD C E", 1 }, { "LD C H", 1 }, { "LD C L", 1 }, { "LD C (HL)", 1 }, { "LD C A", 1 }, { "LD D B", 1 }, { "LD D C", 1 }, { "LD D D", 1 }, { "LD D E", 1 }, { "LD D H", 1 }, { "LD D L", 1 }, { "LD D (HL)", 1 }, { "LD D A", 1 }, { "LD E B", 1 }, { "LD E C", 1 },
{ "LD E D", 1 }, { "LD E E", 1 }, { "LD E H", 1 }, { "LD E L", 1 }, { "LD E (HL)", 1 }, { "LD E A", 1 }, { "LD H B", 1 }, { "LD H C", 1 }, { "LD H D", 1 }, { "LD H E", 1 }, { "LD H H", 1 }, { "LD H L", 1 }, { "LD H (HL)", 1 }, { "LD H A", 1 }, { "LD L B", 1 },
{ "LD L C", 1 }, { "LD L D", 1 }, { "LD L E", 1 }, { "LD L H", 1 }, { "LD L L", 1 }, { "LD L (HL)", 1 }, { "LD L A", 1 }, { "LD (HL) B", 1 }, { "LD (HL) C", 1 }, { "LD (HL) D", 1 }, { "LD (HL) E", 1 }, { "LD (HL) H", 1 }, { "LD (HL) L", 1 }, { "HALT", 1 }, { "LD (HL) A", 1 },
{ "LD A B", 1 }, { "LD A C", 1 }, { "LD A D", 1 }, { "LD A E", 1 }, { "LD A H", 1 }, { "LD A L", 1 }, { "LD A (HL)", 1 }, { "LD A A", 1 }, { "ADD A B", 1 }, { "ADD A C", 1 }, { "ADD A D", 1 }, { "ADD A E", 1 }, { "ADD A H", 1 }, { "ADD A L", 1 }, { "ADD A (HL)", 1 },
{ "ADD A A", 1 }, { "ADC A B", 1 }, { "ADC A C", 1 }, { "ADC A D", 1 }, { "ADC A E", 1 }, { "ADC A H", 1 }, { "ADC A L", 1 }, { "ADC A (HL)", 1 }, { "ADC A A", 1 }, { "SUB B", 1 }, { "SUB C", 1 }, { "SUB D", 1 }, { "SUB E", 1 }, { "SUB H", 1 }, { "SUB L", 1 },
{ "SUB (HL)", 1 }, { "SUB A", 1 }, { "SBC A B", 1 }, { "SBC A C", 1 }, { "SBC A D", 1 }, { "SBC A E", 1 }, { "SBC A H", 1 }, { "SBC A L", 1 }, { "SBC A (HL)", 1 }, { "SBC A A", 1 }, { "AND B", 1 }, { "AND C", 1 }, { "AND D", 1 }, { "AND E", 1 }, { "AND H", 1 },
{ "AND L", 1 }, { "AND (HL)", 1 }, { "AND A", 1 }, { "XOR B", 1 }, { "XOR C", 1 }, { "XOR D", 1 }, { "XOR E", 1 }, { "XOR H", 1 }, { "XOR L", 1 }, { "XOR (HL)", 1 }, { "XOR A", 1 }, { "OR B", 1 }, { "OR C", 1 }, { "OR D", 1 }, { "OR E", 1 },
{ "OR H", 1 }, { "OR L", 1 }, { "OR (HL)", 1 }, { "OR A", 1 }, { "CP B", 1 }, { "CP C", 1 }, { "CP D", 1 }, { "CP E", 1 }, { "CP H", 1 }, { "CP L", 1 }, { "CP (HL)", 1 }, { "CP A", 1 }, { "RET NZ", 1 }, { "POP BC", 1 }, { "JP NZ a16", 3 },
{ "JP a16", 3 }, { "CALL NZ a16", 3 }, { "PUSH BC", 1 }, { "ADD A d8", 2 }, { "RST 00H", 1 }, { "RET Z", 1 }, { "RET", 1 }, { "JP Z a16", 3 }, { "PREFIX", 1 }, { "CALL Z a16", 3 }, { "CALL a16", 3 }, { "ADC A d8", 2 }, { "RST 08H", 1 }, { "RET NC", 1 }, { "POP DE", 1 },
{ "JP NC a16", 3 }, { "ILLEGAL_D3", 1 }, { "CALL NC a16", 3 }, { "PUSH DE", 1 }, { "SUB d8", 2 }, { "RST 10H", 1 }, { "RET C", 1 }, { "RETI", 1 }, { "JP C a16", 3 }, { "ILLEGAL_DB", 1 }, { "CALL C a16", 3 }, { "ILLEGAL_DD", 1 }, { "SBC A d8", 2 }, { "RST 18H", 1 }, { "LDH (a8) A", 2 },
{ "POP HL", 1 }, { "LD (C) A", 1 }, { "ILLEGAL_E3", 1 }, { "ILLEGAL_E4", 1 }, { "PUSH HL", 1 }, { "AND d8", 2 }, { "RST 20H", 1 }, { "ADD SP r8", 2 }, { "JP HL", 1 }, { "LD (a16) A", 3 }, { "ILLEGAL_EB", 1 }, { "ILLEGAL_EC", 1 }, { "ILLEGAL_ED", 1 }, { "XOR d8", 2 }, { "RST 28H", 1 },
{ "LDH A (a8)", 2 }, { "POP AF", 1 }, { "LD A (C)", 1 }, { "DI", 1 }, { "ILLEGAL_F4", 1 }, { "PUSH AF", 1 }, { "OR d8", 2 }, { "RST 30H", 1 }, { "LD HL SP r8", 2 }, { "LD SP HL", 1 }, { "LD A (a16)", 3 }, { "EI", 1 }, { "ILLEGAL_FC", 1 }, { "ILLEGAL_FD", 1 }, { "CP d8", 2 },
{ "RST 38H", 1 }, { "RLC B", 2 }, { "RLC C", 2 }, { "RLC D", 2 }, { "RLC E", 2 }, { "RLC H", 2 }, { "RLC L", 2 }, { "RLC (HL)", 2 }, { "RLC A", 2 }, { "RRC B", 2 }, { "RRC C", 2 }, { "RRC D", 2 }, { "RRC E", 2 }, { "RRC H", 2 }, { "RRC L", 2 },
{ "RRC (HL)", 2 }, { "RRC A", 2 }, { "RL B", 2 }, { "RL C", 2 }, { "RL D", 2 }, { "RL E", 2 }, { "RL H", 2 }, { "RL L", 2 }, { "RL (HL)", 2 }, { "RL A", 2 }, { "RR B", 2 }, { "RR C", 2 }, { "RR D", 2 }, { "RR E", 2 }, { "RR H", 2 },
{ "RR L", 2 }, { "RR (HL)", 2 }, { "RR A", 2 }, { "SLA B", 2 }, { "SLA C", 2 }, { "SLA D", 2 }, { "SLA E", 2 }, { "SLA H", 2 }, { "SLA L", 2 }, { "SLA (HL)", 2 }, { "SLA A", 2 }, { "SRA B", 2 }, { "SRA C", 2 }, { "SRA D", 2 }, { "SRA E", 2 },
{ "SRA H", 2 }, { "SRA L", 2 }, { "SRA (HL)", 2 }, { "SRA A", 2 }, { "SWAP B", 2 }, { "SWAP C", 2 }, { "SWAP D", 2 }, { "SWAP E", 2 }, { "SWAP H", 2 }, { "SWAP L", 2 }, { "SWAP (HL)", 2 }, { "SWAP A", 2 }, { "SRL B", 2 }, { "SRL C", 2 }, { "SRL D", 2 },
{ "SRL E", 2 }, { "SRL H", 2 }, { "SRL L", 2 }, { "SRL (HL)", 2 }, { "SRL A", 2 }, { "BIT 0 B", 2 }, { "BIT 0 C", 2 }, { "BIT 0 D", 2 }, { "BIT 0 E", 2 }, { "BIT 0 H", 2 }, { "BIT 0 L", 2 }, { "BIT 0 (HL)", 2 }, { "BIT 0 A", 2 }, { "BIT 1 B", 2 }, { "BIT 1 C", 2 },
{ "BIT 1 D", 2 }, { "BIT 1 E", 2 }, { "BIT 1 H", 2 }, { "BIT 1 L", 2 }, { "BIT 1 (HL)", 2 }, { "BIT 1 A", 2 }, { "BIT 2 B", 2 }, { "BIT 2 C", 2 }, { "BIT 2 D", 2 }, { "BIT 2 E", 2 }, { "BIT 2 H", 2 }, { "BIT 2 L", 2 }, { "BIT 2 (HL)", 2 }, { "BIT 2 A", 2 }, { "BIT 3 B", 2 },
{ "BIT 3 C", 2 }, { "BIT 3 D", 2 }, { "BIT 3 E", 2 }, { "BIT 3 H", 2 }, { "BIT 3 L", 2 }, { "BIT 3 (HL)", 2 }, { "BIT 3 A", 2 }, { "BIT 4 B", 2 }, { "BIT 4 C", 2 }, { "BIT 4 D", 2 }, { "BIT 4 E", 2 }, { "BIT 4 H", 2 }, { "BIT 4 L", 2 }, { "BIT 4 (HL)", 2 }, { "BIT 4 A", 2 },
{ "BIT 5 B", 2 }, { "BIT 5 C", 2 }, { "BIT 5 D", 2 }, { "BIT 5 E", 2 }, { "BIT 5 H", 2 }, { "BIT 5 L", 2 }, { "BIT 5 (HL)", 2 }, { "BIT 5 A", 2 }, { "BIT 6 B", 2 }, { "BIT 6 C", 2 }, { "BIT 6 D", 2 }, { "BIT 6 E", 2 }, { "BIT 6 H", 2 }, { "BIT 6 L", 2 }, { "BIT 6 (HL)", 2 },
{ "BIT 6 A", 2 }, { "BIT 7 B", 2 }, { "BIT 7 C", 2 }, { "BIT 7 D", 2 }, { "BIT 7 E", 2 }, { "BIT 7 H", 2 }, { "BIT 7 L", 2 }, { "BIT 7 (HL)", 2 }, { "BIT 7 A", 2 }, { "RES 0 B", 2 }, { "RES 0 C", 2 }, { "RES 0 D", 2 }, { "RES 0 E", 2 }, { "RES 0 H", 2 }, { "RES 0 L", 2 },
{ "RES 0 (HL)", 2 }, { "RES 0 A", 2 }, { "RES 1 B", 2 }, { "RES 1 C", 2 }, { "RES 1 D", 2 }, { "RES 1 E", 2 }, { "RES 1 H", 2 }, { "RES 1 L", 2 }, { "RES 1 (HL)", 2 }, { "RES 1 A", 2 }, { "RES 2 B", 2 }, { "RES 2 C", 2 }, { "RES 2 D", 2 }, { "RES 2 E", 2 }, { "RES 2 H", 2 },
{ "RES 2 L", 2 }, { "RES 2 (HL)", 2 }, { "RES 2 A", 2 }, { "RES 3 B", 2 }, { "RES 3 C", 2 }, { "RES 3 D", 2 }, { "RES 3 E", 2 }, { "RES 3 H", 2 }, { "RES 3 L", 2 }, { "RES 3 (HL)", 2 }, { "RES 3 A", 2 }, { "RES 4 B", 2 }, { "RES 4 C", 2 }, { "RES 4 D", 2 }, { "RES 4 E", 2 },
{ "RES 4 H", 2 }, { "RES 4 L", 2 }, { "RES 4 (HL)", 2 }, { "RES 4 A", 2 }, { "RES 5 B", 2 }, { "RES 5 C", 2 }, { "RES 5 D", 2 }, { "RES 5 E", 2 }, { "RES 5 H", 2 }, { "RES 5 L", 2 }, { "RES 5 (HL)", 2 }, { "RES 5 A", 2 }, { "RES 6 B", 2 }, { "RES 6 C", 2 }, { "RES 6 D", 2 },
{ "RES 6 E", 2 }, { "RES 6 H", 2 }, { "RES 6 L", 2 }, { "RES 6 (HL)", 2 }, { "RES 6 A", 2 }, { "RES 7 B", 2 }, { "RES 7 C", 2 }, { "RES 7 D", 2 }, { "RES 7 E", 2 }, { "RES 7 H", 2 }, { "RES 7 L", 2 }, { "RES 7 (HL)", 2 }, { "RES 7 A", 2 }, { "SET 0 B", 2 }, { "SET 0 C", 2 },
{ "SET 0 D", 2 }, { "SET 0 E", 2 }, { "SET 0 H", 2 }, { "SET 0 L", 2 }, { "SET 0 (HL)", 2 }, { "SET 0 A", 2 }, { "SET 1 B", 2 }, { "SET 1 C", 2 }, { "SET 1 D", 2 }, { "SET 1 E", 2 }, { "SET 1 H", 2 }, { "SET 1 L", 2 }, { "SET 1 (HL)", 2 }, { "SET 1 A", 2 }, { "SET 2 B", 2 },
{ "SET 2 C", 2 }, { "SET 2 D", 2 }, { "SET 2 E", 2 }, { "SET 2 H", 2 }, { "SET 2 L", 2 }, { "SET 2 (HL)", 2 }, { "SET 2 A", 2 }, { "SET 3 B", 2 }, { "SET 3 C", 2 }, { "SET 3 D", 2 }, { "SET 3 E", 2 }, { "SET 3 H", 2 }, { "SET 3 L", 2 }, { "SET 3 (HL)", 2 }, { "SET 3 A", 2 },
{ "SET 4 B", 2 }, { "SET 4 C", 2 }, { "SET 4 D", 2 }, { "SET 4 E", 2 }, { "SET 4 H", 2 }, { "SET 4 L", 2 }, { "SET 4 (HL)", 2 }, { "SET 4 A", 2 }, { "SET 5 B", 2 }, { "SET 5 C", 2 }, { "SET 5 D", 2 }, { "SET 5 E", 2 }, { "SET 5 H", 2 }, { "SET 5 L", 2 }, { "SET 5 (HL)", 2 },
{ "SET 5 A", 2 }, { "SET 6 B", 2 }, { "SET 6 C", 2 }, { "SET 6 D", 2 }, { "SET 6 E", 2 }, { "SET 6 H", 2 }, { "SET 6 L", 2 }, { "SET 6 (HL)", 2 }, { "SET 6 A", 2 }, { "SET 7 B", 2 }, { "SET 7 C", 2 }, { "SET 7 D", 2 }, { "SET 7 E", 2 }, { "SET 7 H", 2 }, { "SET 7 L", 2 },
{ "SET 7 (HL)", 2 }, { "SET 7 A", 2 }};